name: Build Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Set up JDK 8'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Build with Gradle'
        id: gradle-build
        run: |
          ./gradlew build --stacktrace
          echo ::set-output name=version::$(./gradlew -q getVersion)

      - name: 'Publish snapshot'
        if: endsWith(${{ steps.gradle-build.outputs.version }}, 'SNAPSHOT')
        run: ./gradlew publish --stacktrace
        env:
          SIGN_ID: ${{ secrets.SIGN_ID }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_PWD: ${{ secrets.SIGN_PWD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: 'dist'
          path: |
            build/*.jar
            !build/*-javadoc.jar
            !build/*-sources.jar
          if-no-files-found: error